name: Azure Pipelines

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- none

# ToDo: Replace the agent pool name, if you are using Udacity Cloud lab. 
# Otherwise, comment out the line below. 
pool: myProject3AgentPool


variables:
  python.version: '3.8.10'
  # ToDo: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: 'project3DemoServiceConn'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: '$(System.DefaultWorkingDirectory)'
  # Environment name
  environmentName: 'test'

stages:

# ------------------------------------------#    
- stage: Deploy_FakeRestAPI
  jobs:
    - job: Deploy_Fakerestapi
      displayName: 'Build and Deploy Fakerestapi'
      pool: myProject3AgentPool
      steps:
      - task: ArchiveFiles@2
        displayName: 'Archive Fakerestapi'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
          verbose: true

      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
          ArtifactName: 'drop-fakerestapi'
        displayName: 'Upload Package'
        
  #--------------------------------------------#  
# DEPLOYMENT STAGE
#--------------------------------------------#    
- stage: Deploy
  jobs:
  #--------------------------------------------#  
  # Deploy FakeRestAPI Web App
  # ToDo: Provide <environment name> you created in your DevOps project
  - deployment: FakeRestAPI
    pool: myProject3AgentPool 
    environment: 'test-vm'
    strategy:
      runOnce:
        deploy:
         
          steps:

          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'current'
              artifact: 'drop-fakerestapi'
              path: '$(Pipeline.Workspace)'
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'Azure subscription 1(bfe3aaca-fcaa-4cf7-8823-0ada2a27d255)'     # ToDo
              appName: 'myApplicationUdacity3-AppService'               # ToDo
              appType: 'webAppLinux'
              package: '$(Pipeline.Workspace)/**/*$(Build.BuildId)-fakerestapi.zip'  
  #--------------------------------------------#  

         
        