name: Azure Pipelines

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- none

# ToDo: Replace the agent pool name, if you are using Udacity Cloud lab. 
# Otherwise, comment out the line below. 
pool: myProject3AgentPool

variables:
  python.version: '3.8.10'
  # ToDo: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: 'project3DemoServiceConn'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: '$(System.DefaultWorkingDirectory)'
  # Environment name
  environmentName: 'test'

stages:

  - stage: Deploy_Fakerestapi
    jobs:
      - job: Deploy_Fakerestapi
        displayName: 'Build and Deploy Fakerestapi'
        pool: myProject3AgentPool
        steps:
        - task: ArchiveFiles@2
          displayName: 'Archive Fakerestapi'
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi'
            includeRootFolder: false
            archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
            verbose: true
        - task: AzureRmWebAppDeployment@4
          displayName: 'Azure App Service Deploy: udacity-AppService'
          inputs:
            azureSubscription: 'Azure subscription 1(bfe3aaca-fcaa-4cf7-8823-0ada2a27d255)'
            WebAppName: 'myApplicationUdacity3-AppService'
            packageForLinux: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
            enableCustomDeployment: true
            DeploymentType: zipDeploy
            TakeAppOfflineFlag: false

    #--------------------------------------------#    
    # FakeRestAPI - Archive
   
         
        